services:
  - type: web
    name: land-classifier
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
    plan: free

