services:
  - type: web
    name: land-classifier
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
    plan: free

